{
  "formatVersion": "1.1",
  "component": {
    "group": "com.violacase",
    "module": "dawnforge",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dawnforge-1.0.jar",
          "url": "dawnforge-1.0.jar",
          "size": 13692,
          "sha512": "9d9fa4bd27797c2bd28db7466a9bb5c06b6bee6aff1390ef1566eca34cf3aaa07cb0968c502c00af31b7d86a4a96c65d33d0448e3fd8c2848efd655adbf6f365",
          "sha256": "613b0229d294b0100ae77d9c40120c58fd244685bee6f7148bb1f2a1d10e8371",
          "sha1": "062ac5ab6e5b5d52cb5cc5a10db12fea2c3b7a17",
          "md5": "5205c67598ec5803845187434e919952"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.20.1-47.4.0_mapped_parchment_2023.09.03-1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "dawnforge-1.0.jar",
          "url": "dawnforge-1.0.jar",
          "size": 13692,
          "sha512": "9d9fa4bd27797c2bd28db7466a9bb5c06b6bee6aff1390ef1566eca34cf3aaa07cb0968c502c00af31b7d86a4a96c65d33d0448e3fd8c2848efd655adbf6f365",
          "sha256": "613b0229d294b0100ae77d9c40120c58fd244685bee6f7148bb1f2a1d10e8371",
          "sha1": "062ac5ab6e5b5d52cb5cc5a10db12fea2c3b7a17",
          "md5": "5205c67598ec5803845187434e919952"
        }
      ]
    }
  ]
}
